# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' National Registry of Construction Works
#'
#' @description
#' Registration, area, economic activity, and responsibility records for
#' Brazilian construction works.
#'
#' Retrieve this dataset with [query_dataset()] using the name `"cno"`.
#'
#' ```r
#' cno <- query_dataset("cno")
#' cno$constructions
#' ```
#'
#' @details
#' * **Source**: Receita Federal do Brasil - Cadastro Nacional de Obras
#' * **URL**: <https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-de-obras-cno>
#' * **Geography**: Brazil
#' * **Frequency**: annual snapshots
#' * **Coverage**: November 2018-present, including migrated CEI records with earlier start dates
#' * **Access mode**: `query`
#' * **Tables**: `"constructions"`, `"areas"`, `"cnaes"`, `"responsibilities"`
#'
#' Column names are normalized to English, while source labels and anomalous
#' values are retained without analytical cleaning.
#'
#' @section Table "constructions" (Constructions):
#' One row per CNO registration.
#'
#' \describe{
#'   \item{cno}{Twelve-digit CNO registration identifier. Stored as character to preserve leading zeroes.}
#'   \item{country_code}{Three-digit country code published by Receita Federal.}
#'   \item{country_name}{Country name published by Receita Federal.}
#'   \item{start_date}{Declared start date of the construction work. Historical sentinel values are retained.}
#'   \item{responsibility_start_date}{Start date of the current responsibility period.}
#'   \item{registration_date}{Date on which the work was registered in CNO.}
#'   \item{linked_cno}{Linked CNO registration when supplied by Receita Federal.}
#'   \item{postal_code}{Postal code for works in Brazil. Stored as character.}
#'   \item{responsible_tax_id}{Fourteen-digit identifier of the responsible legal person. Receita Federal suppresses CPF values.}
#'   \item{responsible_role_code}{Four-digit code for the responsible party's role.}
#'   \item{construction_name}{Name assigned to the construction, not the responsible party's name.}
#'   \item{municipality_tom_code}{Four-digit Receita Federal TOM municipality code, not an IBGE municipality code.}
#'   \item{municipality_name}{Municipality name published by Receita Federal.}
#'   \item{street_type}{Street type.}
#'   \item{street_name}{Street name.}
#'   \item{street_number}{Street number or other source value such as S/N.}
#'   \item{neighborhood}{Neighborhood name.}
#'   \item{state}{State field as published. Usually a two-letter UF abbreviation; source anomalies are retained.}
#'   \item{postal_box}{Postal box for works outside Brazil.}
#'   \item{address_complement}{Additional address information.}
#'   \item{measurement_unit}{Unit used to measure the work.}
#'   \item{total_area}{Total measurement reported for the work, expressed in measurement_unit. Source outliers are retained.}
#'   \item{status_code}{Two-digit CNO status code.}
#'   \item{status_date}{Date associated with the current status.}
#'   \item{responsible_legal_name}{Legal name of the responsible legal person when published.}
#'   \item{plus_code}{Location code published by Receita Federal. Invalid and sentinel source values are retained.}
#' }
#'
#' @section Table "areas" (Construction Areas):
#' Area records classified by category, destination, structure, and area type.
#'
#' \describe{
#'   \item{cno}{CNO registration identifier joining to constructions.cno.}
#'   \item{construction_category}{Category reported for the construction area.}
#'   \item{destination}{Intended use reported for the work area.}
#'   \item{structure_type}{Construction structure type.}
#'   \item{area_type}{Principal or complementary area.}
#'   \item{complementary_area_type}{Complementary-area classification, when applicable.}
#'   \item{area}{Reported area in square metres. Source duplicates and outliers are retained.}
#' }
#'
#' @section Table "cnaes" (Economic Activities):
#' CNAE economic activities associated with each construction work.
#'
#' \describe{
#'   \item{cno}{CNO registration identifier joining to constructions.cno.}
#'   \item{cnae}{Seven-digit CNAE activity code. Stored as character.}
#'   \item{registration_date}{Date on which the activity was registered.}
#' }
#'
#' @section Table "responsibilities" (Responsibility Periods):
#' Responsible-party roles and their periods for each construction work.
#'
#' \describe{
#'   \item{cno}{CNO registration identifier joining to constructions.cno.}
#'   \item{start_date}{Start date of the responsibility period.}
#'   \item{end_date}{End date of the responsibility period, when applicable.}
#'   \item{registration_date}{Date on which the responsibility was registered.}
#'   \item{responsible_role_code}{Four-digit code for the responsible party's role.}
#'   \item{responsible_tax_id}{Fourteen-digit identifier of the responsible legal person. Receita Federal suppresses CPF values.}
#' }
#'
#' @source Receita Federal do Brasil - Cadastro Nacional de Obras
#' @seealso [get_dataset()], [query_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name cno
NULL
