# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' PNAD Contínua Housing
#'
#' @description
#' Annual household tenure, dwelling type, household size, and domestic-unit
#' composition estimates from PNAD Contínua.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"pnad_housing"`.
#'
#' ```r
#' pnad_housing <- get_dataset("pnad_housing")
#' pnad_housing_dwelling_type <- get_dataset("pnad_housing", table = "dwelling_type")
#' ```
#'
#' @details
#' * **Source**: IBGE - Pesquisa Nacional por Amostra de Domicílios Contínua anual
#' * **URL**: <https://sidra.ibge.gov.br/pesquisa/pnadca/tabelas>
#' * **Geography**: Brazil, geographic regions, states, state capitals, published metropolitan regions, and published integrated-development regions
#' * **Frequency**: annual
#' * **Coverage**: 2016-2025 for housing-module tables, excluding 2020-2021; 2012-2025 for household composition
#' * **Access mode**: `materialized`
#' * **Tables**: `"tenure"`, `"dwelling_type"`, `"household_size"`, `"mean_household_size"`, `"household_composition"` (default: `"tenure"`)
#'
#' Counts remain in thousand households, percentages remain on a 0-100 scale,
#' and coefficients of variation are separate measures. Total categories
#' coexist with component categories and must be excluded before summing
#' components. Housing-module tables have no 2020-2021 observations. Household
#' composition describes relationships to the reference person, not a number
#' of families; its published count rows are restricted to total
#' reference-person sex. Geography labels retain the boundary-vintage text
#' published by IBGE.
#'
#' @section Columns:
#' All tables share the structure below; the `table` argument filters which
#' series are returned.
#'
#' \describe{
#'   \item{year}{Reference year.}
#'   \item{source_table}{SIDRA table supplying the observation.}
#'   \item{geography_type}{Geographic level: brazil, region, state, capital, metropolitan_region, or integrated_development_region.}
#'   \item{geography_code}{IBGE code for the geographic unit; interpret together with geography_type.}
#'   \item{geography_name}{Geographic unit name in Portuguese, including the source boundary-vintage text.}
#'   \item{geography_level_name}{Original SIDRA geographic-level label in Portuguese.}
#'   \item{classification_id}{SIDRA classification ID; missing for mean_household_size.}
#'   \item{category_id}{SIDRA category ID; missing for mean_household_size.}
#'   \item{category}{Stable English category identifier; missing for mean_household_size.}
#'   \item{category_name_pt}{Original SIDRA category label in Portuguese; missing for mean_household_size.}
#'   \item{variable_id}{SIDRA variable ID.}
#'   \item{variable}{Stable English measure identifier.}
#'   \item{variable_name_pt}{Original IBGE variable label in Portuguese.}
#'   \item{unit}{Original IBGE unit: Mil unidades, Pessoas, or percent.}
#'   \item{value}{Observed value in the original unit; NA when the cell is not applicable, not available, suppressed, or missing.}
#'   \item{value_raw}{Original SIDRA cell text.}
#'   \item{value_status}{Cell status: observed, zero, not_applicable, not_available, suppressed, or missing.}
#' }
#'
#' @source IBGE - Pesquisa Nacional por Amostra de Domicílios Contínua anual
#' @seealso [get_dataset()], [query_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name pnad_housing
NULL
