# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' FGV IBRE Real Estate Indicators
#'
#' @description
#' Real estate market indicators from Fundação Getulio Vargas IBRE.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"fgv_ibre"`.
#'
#' ```r
#' fgv_ibre <- get_dataset("fgv_ibre")
#' ```
#'
#' @details
#' * **Source**: FGV IBRE
#' * **URL**: <https://portalibre.fgv.br>
#' * **Geography**: Brazil
#' * **Frequency**: monthly
#' * **Coverage**: 2010-present
#'
#' Technical economic terms; standard translations applied.
#'
#' @section Columns:
#' \describe{
#'   \item{date}{Reference month.}
#'   \item{name_simplified}{Short series identifier (e.g. incc_brasil_di, ivar_brazil, ic_cst).}
#'   \item{value}{Series value.}
#'   \item{name_series}{Full series name in Portuguese.}
#'   \item{code_series}{FGV series code.}
#'   \item{unit}{Unit of the series (index, percent, or indicator).}
#'   \item{source}{FGV survey of origin (e.g. FGV-INCC, FGV-SONDA).}
#' }
#'
#' @source FGV IBRE
#' @seealso [get_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name fgv_ibre
NULL
