# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' ABRAINC-FIPE Primary Market Indicators
#'
#' @description
#' Primary real estate market indicators including launches, sales, and
#' business conditions from 66+ partnered developers.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"abrainc"`.
#'
#' ```r
#' abrainc <- get_dataset("abrainc")
#' abrainc_radar <- get_dataset("abrainc", table = "radar")
#' ```
#'
#' @details
#' * **Source**: ABRAINC/FIPE
#' * **URL**: <https://www.fipe.org.br/pt-br/indices/abrainc>
#' * **Geography**: Brazil (major cities)
#' * **Frequency**: quarterly
#' * **Coverage**: 2014-present
#' * **Tables**: `"indicator"`, `"radar"`, `"leading"` (default: `"indicator"`)
#'
#' Social Housing (MCMV) refers to Minha Casa Minha Vida and Casa Verde
#' Amarela programs.
#'
#' @section Table "indicator" (Market Indicators):
#' Broad numbers of launches, sales, supply in the primary market. This is the
#' default table.
#'
#' \describe{
#'   \item{date}{Reference month.}
#'   \item{year}{Reference year.}
#'   \item{category}{Indicator group (e.g. new_units, sold, delivered).}
#'   \item{variable}{Market segment: total, market_rate, or social_housing (MCMV and related programs).}
#'   \item{value}{Number of units.}
#'   \item{variable_label}{Human-readable label for variable.}
#' }
#'
#' @section Table "radar" (Business Radar):
#' 0-10 standardized index for general business conditions.
#'
#' \describe{
#'   \item{date}{Reference month.}
#'   \item{year}{Reference year.}
#'   \item{category}{Radar dimension (e.g. macro, credit, demand).}
#'   \item{variable}{Indicator within the dimension (e.g. confidence, activity, interest).}
#'   \item{source}{Source of the underlying series (e.g. FGV, BCB).}
#'   \item{value}{Standardized 0-10 score.}
#'   \item{avg_category}{Average score of the category over the full sample.}
#'   \item{avg_year_category}{Average score of the category in the year.}
#'   \item{avg_year_variable}{Average score of the variable in the year.}
#'   \item{ma3}{3-month moving average of value.}
#'   \item{ma6}{6-month moving average of value.}
#'   \item{variable_label}{Human-readable label for variable.}
#' }
#'
#' @section Table "leading" (Leading Indicator):
#' Building permits in São Paulo as real estate leading indicator.
#'
#' \describe{
#'   \item{date}{Reference month.}
#'   \item{year}{Reference year.}
#'   \item{variable}{Series identifier: leading_index, leading_index_12m, or alvaras_total (building permits).}
#'   \item{zone}{São Paulo city zone (Total, Centro, Zona Norte, and others).}
#'   \item{value}{Series value; index points, percent change, or permit counts depending on variable.}
#'   \item{variable_label}{Human-readable label for variable.}
#' }
#'
#' @source ABRAINC/FIPE
#' @seealso [get_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name abrainc
NULL
