# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' PAIC Construction Industry Data
#'
#' @description
#' Annual construction-industry activity, employment, revenue, costs, and
#' output for the new series starting in 2024.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"paic"`.
#'
#' ```r
#' paic <- get_dataset("paic")
#' paic_size <- get_dataset("paic", table = "size")
#' ```
#'
#' @details
#' * **Source**: IBGE - Pesquisa Anual da Indústria da Construção
#' * **URL**: <https://sidra.ibge.gov.br/pesquisa/paic/tabelas>
#' * **Geography**: Brazil, geographic regions, and states (varies by table)
#' * **Frequency**: annual
#' * **Coverage**: 2024-present (new series; do not compare with 2007-2023)
#' * **Access mode**: `materialized`
#' * **Tables**: `"activity"`, `"size"`, `"state"` (default: `"activity"`)
#'
#' New 2024-onward series per IBGE Nota técnica 01/2026; the 2024 series break
#' reflects the new Cadastro Básico de Seleção. Values publish in original
#' units, including thousand reais. Table 10463 covers all firms at national
#' level only; table 10442 covers firms with five or more workers by
#' headquarters or work location.
#'
#' @section Table "activity" (Activity by Size Band):
#' General construction-enterprise data by firm-size band and CNAE activity
#' from SIDRA table 10463 (Brazil only, all firms). The hierarchy stacks
#' totals, divisions, groups, and classes in one tibble; filter by
#' activity_level to avoid double-counting. Detail differs by size band: 1-4
#' workers reaches divisions only, 5-29 adds groups, and 30+ reaches classes.
#' No category covers all sizes for a single division; the only all-firm row
#' is Total das empresas, so a national division total is the sum of the three
#' size bands.. This is the default table.
#' Coverage: 2024-present.
#'
#' \describe{
#'   \item{year}{Reference year.}
#'   \item{source_table}{SIDRA table supplying the observation (10463).}
#'   \item{geography_type}{Geographic level (brazil for this table).}
#'   \item{geography_code}{IBGE code for the geographic unit.}
#'   \item{geography_name}{Geographic unit name in Portuguese.}
#'   \item{size_band}{Firm-size band: total, 1_4, 5_29, or 30_plus.}
#'   \item{activity_level}{CNAE level: total, division, group, or class.}
#'   \item{activity_code}{CNAE 2.0 code parsed from the category (e.g. 41, 41.1, 41.10); missing for totals.}
#'   \item{activity_name}{Canonical CNAE activity name from the package lookup.}
#'   \item{division_code}{Parent CNAE division code.}
#'   \item{group_code}{Parent CNAE group code (for groups and classes).}
#'   \item{variable_id}{SIDRA variable ID.}
#'   \item{variable}{English series identifier (e.g. firms, employment, wages, construction_output).}
#'   \item{variable_name_pt}{Original IBGE variable label in Portuguese.}
#'   \item{unit}{Original IBGE unit, including thousand reais (Mil Reais) where specified.}
#'   \item{value}{Observed value; SIDRA dash (-) is absolute zero.}
#'   \item{value_raw}{Original SIDRA cell text.}
#'   \item{value_status}{Cell status: observed, zero, not_applicable (..), not_available (...), suppressed (X), or missing.}
#' }
#'
#' @section Table "size" (Size Bands by Geography):
#' General construction-enterprise data by firm-size band from SIDRA table
#' 10441 (Brazil, regions, and states, all firms). Keeps the 16 level
#' variables; the 16 share variables (percentual do total geral) are dropped
#' because users can derive them..
#' Coverage: 2024-present.
#'
#' \describe{
#'   \item{year}{Reference year.}
#'   \item{source_table}{SIDRA table supplying the observation (10441).}
#'   \item{geography_type}{Geographic level: brazil, region, or state.}
#'   \item{geography_code}{IBGE code for the geographic unit; interpret together with geography_type.}
#'   \item{geography_name}{Geographic unit name in Portuguese.}
#'   \item{size_band}{Firm-size band: total, 1_4, or 5_plus.}
#'   \item{variable_id}{SIDRA variable ID.}
#'   \item{variable}{English series identifier (e.g. firms, employment, wages, construction_output).}
#'   \item{variable_name_pt}{Original IBGE variable label in Portuguese.}
#'   \item{unit}{Original IBGE unit, including thousand reais (Mil Reais) where specified.}
#'   \item{value}{Observed value; SIDRA dash (-) is absolute zero.}
#'   \item{value_raw}{Original SIDRA cell text.}
#'   \item{value_status}{Cell status: observed, zero, not_applicable (..), not_available (...), suppressed (X), or missing.}
#' }
#'
#' @section Table "state" (Large Firms by State):
#' Employment, wages, costs, and output for construction firms with five or
#' more workers from SIDRA table 10442 (Brazil, regions, and states). The
#' geography_basis column records whether the variable follows headquarters
#' (13807, origem-sede) or work location (all other variables, local de
#' atuação)..
#' Coverage: 2024-present.
#'
#' \describe{
#'   \item{year}{Reference year.}
#'   \item{source_table}{SIDRA table supplying the observation (10442).}
#'   \item{geography_type}{Geographic level: brazil, region, or state.}
#'   \item{geography_code}{IBGE code for the geographic unit; interpret together with geography_type.}
#'   \item{geography_name}{Geographic unit name in Portuguese.}
#'   \item{geography_basis}{Geographic meaning: headquarters (variable 13807) or work_location (all other variables).}
#'   \item{variable_id}{SIDRA variable ID.}
#'   \item{variable}{English series identifier (e.g. employment, wages, construction_output).}
#'   \item{variable_name_pt}{Original IBGE variable label in Portuguese.}
#'   \item{unit}{Original IBGE unit, including thousand reais (Mil Reais) where specified.}
#'   \item{value}{Observed value; SIDRA dash (-) is absolute zero.}
#'   \item{value_raw}{Original SIDRA cell text.}
#'   \item{value_status}{Cell status: observed, zero, not_applicable (..), not_available (...), suppressed (X), or missing.}
#' }
#'
#' @source IBGE - Pesquisa Anual da Indústria da Construção
#' @seealso [get_dataset()], [query_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name paic
NULL
