# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' BCB Real Estate Market Data
#'
#' @description
#' Comprehensive real estate credit and market data from Brazilian Central
#' Bank.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"bcb_realestate"`.
#'
#' ```r
#' bcb_realestate <- get_dataset("bcb_realestate")
#' bcb_realestate_accounting <- get_dataset("bcb_realestate", table = "accounting")
#' ```
#'
#' @details
#' * **Source**: Banco Central do Brasil
#' * **URL**: <https://dadosabertos.bcb.gov.br/dataset/informacoes-do-mercado-imobiliario>
#' * **Geography**: Brazil (by state)
#' * **Frequency**: monthly
#' * **Coverage**: 2001-present (varies by category)
#' * **Tables**: `"accounting"`, `"application"`, `"indices"`, `"sources"`, `"units"` (default: `"all"`)
#'
#' Complex multi-level series structure; v1-v5 columns contain series
#' components.
#'
#' @section Columns:
#' All tables share the structure below; the `table` argument filters which
#' series are returned.
#'
#' \describe{
#'   \item{date}{End-of-month reference date (last day of the month).}
#'   \item{category}{Top-level series grouping (e.g. credito, contabil, direcionamento, fontes, imoveis).}
#'   \item{type}{Series subtype within the category (e.g. estoque, contratacao, financiamento).}
#'   \item{v1}{Series identifier component 1; meaning varies by series (e.g. carteira, borrower type, region).}
#'   \item{v2}{Series identifier component 2 (e.g. br, pf, pj).}
#'   \item{v3}{Series identifier component 3 (e.g. credit line such as sfh, fgts, home-equity).}
#'   \item{v4}{Series identifier component 4 (often a state abbreviation or credit line).}
#'   \item{v5}{Series identifier component 5 (often a state abbreviation or br).}
#'   \item{series_info}{Full underscore-separated series identifier; together with date it uniquely identifies an observation.}
#'   \item{value}{Series value; unit varies by series (R$, units, or percent).}
#'   \item{year}{Reference year.}
#'   \item{month}{Reference month (1-12).}
#'   \item{abbrev_state}{Two-letter state abbreviation, or BR for the national aggregate.}
#' }
#'
#' @source Banco Central do Brasil
#' @seealso [get_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name bcb_realestate
NULL
