# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' SINAPI Construction Costs and Indices
#'
#' @description
#' Monthly construction costs, cost indices, and percentage changes from the
#' National System of Construction Costs and Indices.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"sinapi"`.
#'
#' ```r
#' sinapi <- get_dataset("sinapi")
#' ```
#'
#' @details
#' * **Source**: IBGE - Sistema Nacional de Pesquisa de Custos e Índices da Construção Civil
#' * **URL**: <https://sidra.ibge.gov.br/tabela/2296>
#' * **Geography**: Brazil, geographic regions, and states
#' * **Frequency**: monthly
#' * **Coverage**: March 1986-present (varies by series)
#' * **Access mode**: `materialized`
#'
#' Data come from SIDRA table 2296. Monetary series are expressed in the
#' currency reported by IBGE for each historical period.
#'
#' @section Columns:
#' \describe{
#'   \item{date}{First day of the reference month.}
#'   \item{geography_type}{Geographic level: brazil, region, or state.}
#'   \item{geography_code}{IBGE code for the geographic unit; interpret together with geography_type.}
#'   \item{geography_name}{Geographic unit name in Portuguese.}
#'   \item{variable}{Series identifier: cost, materials_cost, labor_cost, cost_index, materials_index, labor_index, monthly_change, year_to_date_change, or twelve_month_change.}
#'   \item{variable_label}{Original IBGE variable label in Portuguese.}
#'   \item{unit}{Original IBGE unit: Reais, Número-índice, or percent.}
#'   \item{value}{Observed value. Missing values and periods not covered by a series are omitted.}
#' }
#'
#' @source IBGE - Sistema Nacional de Pesquisa de Custos e Índices da Construção Civil
#' @seealso [get_dataset()], [query_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name sinapi
NULL
