# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' BIS Residential Property Price Indices
#'
#' @description
#' International residential property price indices from Bank for
#' International Settlements.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"rppi_bis"`.
#'
#' ```r
#' rppi_bis <- get_dataset("rppi_bis")
#' rppi_bis_detailed_monthly <- get_dataset("rppi_bis", table = "detailed_monthly")
#' ```
#'
#' @details
#' * **Source**: Bank for International Settlements
#' * **URL**: <https://data.bis.org/topics/RPP>
#' * **Geography**: International (60+ countries including Brazil)
#' * **Frequency**: quarterly
#' * **Coverage**: 1970-present (varies by country)
#' * **Tables**: `"selected"`, `"detailed_monthly"`, `"detailed_quarterly"`, `"detailed_annual"`, `"detailed_halfyearly"` (default: `"selected"`)
#'
#' International data; minimal translation needed.
#'
#' @section Table "selected" (Selected Series):
#' Core RPPI series for major countries. This is the default table.
#'
#' \describe{
#'   \item{date}{Reference quarter (first day of the quarter).}
#'   \item{ref_area_code}{Country or area code (aggregates use BIS codes such as 4T).}
#'   \item{ref_area_name}{Country or area name.}
#'   \item{unit}{Measure: index (2010 = 100) or yoy_chg (year-on-year change, percent).}
#'   \item{unit_name}{Full description of the unit of measure.}
#'   \item{is_nominal}{1 for nominal series, 0 for CPI-deflated (real) series.}
#'   \item{series_code}{BIS series identifier.}
#'   \item{value}{Series value.}
#' }
#'
#' @section Table "detailed_monthly" (Detailed Monthly):
#' Monthly detailed RPPI data.
#'
#' \describe{
#'   \item{date}{Reference period.}
#'   \item{year}{Reference year.}
#'   \item{series_code}{BIS series identifier.}
#'   \item{ref_area_code}{Country or area code.}
#'   \item{ref_area_name}{Country or area name.}
#'   \item{re_type_code}{Property type code.}
#'   \item{re_type_name}{Property type (e.g. all types, new or existing dwellings).}
#'   \item{re_vintage_code}{Property vintage code.}
#'   \item{re_vintage_name}{Property vintage (new versus existing).}
#'   \item{compiling_org_code}{Compiling organisation code.}
#'   \item{compiling_org_name}{Compiling organisation.}
#'   \item{priced_unit_code}{Priced unit code.}
#'   \item{priced_unit_name}{Priced unit (e.g. dwelling, square metre).}
#'   \item{seas_adjust_code}{Seasonal adjustment code.}
#'   \item{seas_adjust_name}{Seasonal adjustment description.}
#'   \item{availability_code}{Series availability code.}
#'   \item{availability_name}{Series availability description.}
#'   \item{unit_code}{Unit of measure code.}
#'   \item{unit_name}{Unit of measure description.}
#'   \item{unit_mult_code}{Unit multiplier code.}
#'   \item{unit_mult_name}{Unit multiplier description.}
#'   \item{value}{Series value.}
#' }
#'
#' Frequency-specific period columns (month, quarter, or semester) and a few
#' metadata columns vary slightly across the detailed tables.
#'
#' @section Table "detailed_quarterly" (Detailed Quarterly):
#' Quarterly detailed RPPI data.
#'
#' \describe{
#'   \item{date}{Reference period.}
#'   \item{year}{Reference year.}
#'   \item{series_code}{BIS series identifier.}
#'   \item{ref_area_code}{Country or area code.}
#'   \item{ref_area_name}{Country or area name.}
#'   \item{re_type_code}{Property type code.}
#'   \item{re_type_name}{Property type (e.g. all types, new or existing dwellings).}
#'   \item{re_vintage_code}{Property vintage code.}
#'   \item{re_vintage_name}{Property vintage (new versus existing).}
#'   \item{compiling_org_code}{Compiling organisation code.}
#'   \item{compiling_org_name}{Compiling organisation.}
#'   \item{priced_unit_code}{Priced unit code.}
#'   \item{priced_unit_name}{Priced unit (e.g. dwelling, square metre).}
#'   \item{seas_adjust_code}{Seasonal adjustment code.}
#'   \item{seas_adjust_name}{Seasonal adjustment description.}
#'   \item{availability_code}{Series availability code.}
#'   \item{availability_name}{Series availability description.}
#'   \item{unit_code}{Unit of measure code.}
#'   \item{unit_name}{Unit of measure description.}
#'   \item{unit_mult_code}{Unit multiplier code.}
#'   \item{unit_mult_name}{Unit multiplier description.}
#'   \item{value}{Series value.}
#' }
#'
#' @section Table "detailed_annual" (Detailed Annual):
#' Annual detailed RPPI data.
#'
#' \describe{
#'   \item{date}{Reference period.}
#'   \item{year}{Reference year.}
#'   \item{series_code}{BIS series identifier.}
#'   \item{ref_area_code}{Country or area code.}
#'   \item{ref_area_name}{Country or area name.}
#'   \item{re_type_code}{Property type code.}
#'   \item{re_type_name}{Property type (e.g. all types, new or existing dwellings).}
#'   \item{re_vintage_code}{Property vintage code.}
#'   \item{re_vintage_name}{Property vintage (new versus existing).}
#'   \item{compiling_org_code}{Compiling organisation code.}
#'   \item{compiling_org_name}{Compiling organisation.}
#'   \item{priced_unit_code}{Priced unit code.}
#'   \item{priced_unit_name}{Priced unit (e.g. dwelling, square metre).}
#'   \item{seas_adjust_code}{Seasonal adjustment code.}
#'   \item{seas_adjust_name}{Seasonal adjustment description.}
#'   \item{availability_code}{Series availability code.}
#'   \item{availability_name}{Series availability description.}
#'   \item{unit_code}{Unit of measure code.}
#'   \item{unit_name}{Unit of measure description.}
#'   \item{unit_mult_code}{Unit multiplier code.}
#'   \item{unit_mult_name}{Unit multiplier description.}
#'   \item{value}{Series value.}
#' }
#'
#' @section Table "detailed_halfyearly" (Detailed Half-yearly):
#' Half-yearly detailed RPPI data.
#'
#' \describe{
#'   \item{date}{Reference period.}
#'   \item{year}{Reference year.}
#'   \item{series_code}{BIS series identifier.}
#'   \item{ref_area_code}{Country or area code.}
#'   \item{ref_area_name}{Country or area name.}
#'   \item{re_type_code}{Property type code.}
#'   \item{re_type_name}{Property type (e.g. all types, new or existing dwellings).}
#'   \item{re_vintage_code}{Property vintage code.}
#'   \item{re_vintage_name}{Property vintage (new versus existing).}
#'   \item{compiling_org_code}{Compiling organisation code.}
#'   \item{compiling_org_name}{Compiling organisation.}
#'   \item{priced_unit_code}{Priced unit code.}
#'   \item{priced_unit_name}{Priced unit (e.g. dwelling, square metre).}
#'   \item{seas_adjust_code}{Seasonal adjustment code.}
#'   \item{seas_adjust_name}{Seasonal adjustment description.}
#'   \item{availability_code}{Series availability code.}
#'   \item{availability_name}{Series availability description.}
#'   \item{unit_code}{Unit of measure code.}
#'   \item{unit_name}{Unit of measure description.}
#'   \item{unit_mult_code}{Unit multiplier code.}
#'   \item{unit_mult_name}{Unit multiplier description.}
#'   \item{value}{Series value.}
#' }
#'
#' @source Bank for International Settlements
#' @seealso [get_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name rppi_bis
NULL
