# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' SECOVI-SP Real Estate Market Data
#'
#' @description
#' São Paulo real estate market indicators including condominium fees,
#' rentals, launches, and sales.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"secovi"`.
#'
#' ```r
#' secovi <- get_dataset("secovi")
#' secovi_condo <- get_dataset("secovi", table = "condo")
#' ```
#'
#' @details
#' * **Source**: SECOVI-SP - Sindicato da Habitação
#' * **URL**: <https://www.secovi.com.br>
#' * **Geography**: São Paulo
#' * **Frequency**: monthly
#' * **Coverage**: 2004-present (varies by category)
#' * **Tables**: `"condo"`, `"rent"`, `"launch"`, `"sale"` (default: `"all"`)
#'
#' Regional classifications are specific to the São Paulo metropolitan area.
#' SECOVI no longer publishes indicators 25 (`launches_rmsp`) and 118
#' (`sales_rmsp`), so they are not returned.
#'
#' @section Columns:
#' All tables share the structure below; the `table` argument filters which
#' series are returned.
#'
#' \describe{
#'   \item{date}{Reference month.}
#'   \item{category}{Market segment: condo, rent, launch, or sale.}
#'   \item{variable}{Indicator within the category (e.g. icon, default_condominio, acao_locaticia).}
#'   \item{name}{Breakdown dimension of the indicator (region, property type, or total).}
#'   \item{value}{Indicator value; unit varies by variable.}
#' }
#'
#' @source SECOVI-SP - Sindicato da Habitação
#' @seealso [get_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name secovi
NULL
