# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' BCB Economic Series
#'
#' @description
#' General economic and real estate related time series from Brazilian Central
#' Bank.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"bcb_series"`.
#'
#' ```r
#' bcb_series <- get_dataset("bcb_series")
#' bcb_series_primary <- get_dataset("bcb_series", table = "primary")
#' ```
#'
#' @details
#' * **Source**: Banco Central do Brasil - SGS
#' * **URL**: <https://www3.bcb.gov.br/sgspub>
#' * **Geography**: Brazil
#' * **Frequency**: varies (daily/monthly/quarterly)
#' * **Coverage**: varies by series
#' * **Tables**: `"core"`, `"primary"`, `"secondary"`, `"tertiary"`, `"full"` (default: `"core"`)
#'
#' Metadata available in both Portuguese and English.
#'
#' @section Columns:
#' All tables share the structure below; the `table` argument filters which
#' series are returned.
#'
#' \describe{
#'   \item{date}{Reference date (frequency varies by series).}
#'   \item{code_bcb}{Numeric code of the series in the BCB SGS system.}
#'   \item{name_simplified}{Short series identifier; see the bundled bcb_metadata table for full names and units.}
#'   \item{value}{Series value.}
#' }
#'
#' @source Banco Central do Brasil - SGS
#' @seealso [get_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name bcb_series
NULL
