# Generated by data-raw/generate_dataset_docs.R from inst/extdata/datasets.yaml
# Do not edit by hand; edit the registry and re-run the generator.

#' PIM-PF Construction-input Production Index
#'
#' @description
#' Linked monthly physical-production index for inputs typically used in
#' construction.
#'
#' Retrieve this dataset with [get_dataset()] using the name `"pim_pf_construction"`.
#'
#' ```r
#' pim_pf_construction <- get_dataset("pim_pf_construction")
#' ```
#'
#' @details
#' * **Source**: IBGE - Pesquisa Industrial Mensal - Produção Física
#' * **URL**: <https://sidra.ibge.gov.br/tabela/8886>
#' * **Geography**: Brazil
#' * **Frequency**: monthly
#' * **Coverage**: January 1991-present
#' * **Access mode**: `materialized`
#'
#' The 1991-2011 series from SIDRA table 2294 is linked to table 8886 using
#' their full 2012 overlap.
#'
#' @section Columns:
#' \describe{
#'   \item{date}{First day of the reference month.}
#'   \item{variable}{Series identifier: construction_inputs_production_index.}
#'   \item{reference_period}{Reference period of the linked index: 2022 average = 100.}
#'   \item{source_table}{SIDRA table supplying the observation: 2294 before 2012 and 8886 from 2012 onward.}
#'   \item{value}{Linked physical-production index. Values before 2012 are rescaled by the ratio of the two source series' 2012 annual means.}
#' }
#'
#' @source IBGE - Pesquisa Industrial Mensal - Produção Física
#' @seealso [get_dataset()], [query_dataset()], [list_datasets()], [get_dataset_info()]
#' @family datasets
#' @keywords datasets
#' @name pim_pf_construction
NULL
