name: Update Real Estate Data

on:
  schedule:
    - cron: '0 0 */14 * *'  # Runs every 14 days at 00:00 UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::vroom
            any::here
            any::readr
            any::devtools
            any::usethis
            any::remotes
            any::desc

      - name: Install package from current repository
        run: |
          Rscript -e 'remotes::install_local(".", dependencies = TRUE)'

      - name: Create directories
        run: |
          mkdir -p cached_data
          mkdir -p data

      - name: Run data update script
        run: Rscript 'data-raw/update_data.R'

      - name: Update package data and documentation
        run: |
          Rscript -e 'devtools::document()'
          Rscript -e 'current_version <- desc::desc_get_version(); version_parts <- unclass(current_version)[[1]]; new_version <- paste(version_parts[1], version_parts[2], version_parts[3] + 1, sep = "."); desc::desc_set_version(new_version)'

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add cached_data/
          git add data/
          git add DESCRIPTION
          git add man/
          git commit -m "Weekly data update: $(date +%Y-%m-%d)" || echo "No changes to commit"
          git push https://$GITHUB_TOKEN@github.com/${GITHUB_REPOSITORY}.git HEAD:$GITHUB_REF || echo "No changes to push"

      - name: Check for errors
        if: failure()
        run: |
          echo "The workflow failed. Check the logs for details."
          exit 1
